In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import os 
import joblib # to save our model that created
plt.style.use("fivethirtyeight")

In [15]:
class perceptron:
    def __init__(self,eta:float =None, epochs:int=None):
        self.weights=np.random.randn(3)*1e-4     #le4 =10^-4
        self.eta = eta  #learning rate
        self.epochs=epochs
        
    def fit(self,x,y):
        self.x=x
        self.y=y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]  # concatinating x with bias 
        print(f"x with bias: \n {x_with_bias}")
    

In [16]:
obj = perceptron(eta=0.01,epochs=20)

In [17]:
obj.weights

array([-8.79318785e-05, -5.19218304e-05,  1.75335612e-05])

In [18]:
y = np.ones((4,1))

In [19]:
x=np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
obj.fit(x,y)

x with bias: 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [36]:
class perceptron:
    def __init__(self,eta:float =None, epochs:int=None):
        self.weights=np.random.randn(3)*1e-4     #le4 =10^-4
        self.eta = eta  #learning rate
        self.epochs=epochs
        
    def _z_outcome(self,inputs,weights):    # hidden method
        return np.dot(inputs,weights)  # gives dot product
        
    def activation_function(self,z):
        return np.where(z>0,1, 0)
        
    def fit(self,x,y):
        self.x=x
        self.y=y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]  # concatinating x with bias 
        print(f"x with bias: \n {x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(x_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: {self.error}")
            
            self.weights = self.weights + self.eta*np.dot(x_with_bias.T,self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def prediction(self,x):  # x=new data
        x_with_bias = np.c_[x, -np.ones((len(x),1))]
        z=self._z_outcome(x_with_bias, self.weights)
        return self.activation_function(z)
            
    

In [37]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [38]:
x = df_OR.drop(columns='y')
y = df_OR['y']
eta = 0.1
epochs=10

model = perceptron(eta=eta,epochs=epochs)

In [39]:
model.fit(x,y)

x with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.199947    0.19981837 -0.29996253]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.199947    0.19981837 -0.19996253]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.199947    0.19981837 -0.09996253]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 0   -1
1    0
2    0
3    0
Name: y, dtype: i

In [34]:
X = [[1,1]]

In [35]:
model.prediction(X)

array([1])